-- Seed legacy providers from the public map CSV
insert into wholesalers (
  name,
  slug,
  provider_type,
  contact_name,
  email,
  phone,
  address,
  city,
  province,
  country,
  instagram,
  website,
  latitude,
  longitude,
  status,
  internal_notes,
  approved_at
)
values
(
  'LO QUE APRENDI DE MAMÁ',
  'lo-que-aprendi-de-mama-la-plata-buenos-aires',
  'distributor',
  null,
  null,
  '542216835246',
  'CALLE 12 Nº 1084 E/ 54 Y 55.',
  'LA PLATA',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.921717',
  '-57.9516278',
  'approved',
  null,
  now()
),
(
  'LO QUE APRENDI DE MAMÁ',
  'lo-que-aprendi-de-mama-city-bell-buenos-aires',
  'distributor',
  null,
  null,
  '542216835246',
  'CALLE CANTILO Nº 166 E/ 13A Y 13B.',
  'CITY BELL',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.8676166',
  '-58.0433429',
  'approved',
  null,
  now()
),
(
  'Mia Hilados MDP',
  'mia-hilados-mdp-mar-del-plata-buenos-aires',
  'wholesaler',
  null,
  null,
  '5492236871679',
  'Alvarado 1202 Guemes',
  'Mar del Plata',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-38.0169992',
  '-57.5415366',
  'approved',
  null,
  now()
),
(
  'Distribuidora Paretta',
  'distribuidora-paretta-marcos-paz-buenos-aires',
  'wholesaler',
  null,
  'https://www.distribuidorapareta.com/',
  '541122672188',
  'Sarmiento 2055',
  'Marcos Paz',
  'Buenos Aires',
  'AR',
  null,
  'https://www.distribuidorapareta.com/',
  '-34.7828307',
  '-58.838965',
  'approved',
  null,
  now()
),
(
  'Lantex',
  'lantex-berazategui-buenos-aires',
  'distributor',
  null,
  null,
  '5492215052387',
  'Av. 14 N° 4818',
  'Berazategui',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.7615286',
  '-58.2091235',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-los-cardales-exaltacion-de-la-cruz-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Estrada 116',
  'Los Cardales, Exaltacion de la Cruz',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.3279172',
  '-58.9842521',
  'approved',
  null,
  now()
),
(
  'Casa Irene',
  'casa-irene-villa-lugano-buenos-aires',
  'distributor',
  null,
  null,
  '541163760094',
  'Av. Riestra 5684',
  'Villa Lugano',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.6771979',
  '-58.4750241',
  'approved',
  null,
  now()
),
(
  'Jaqueline Hilados',
  'jaqueline-hilados-san-justo-buenos-aires',
  'distributor',
  null,
  'https://jaquelinehilados.mitiendanube.com/',
  '5491164308005',
  'Peru 2369',
  'San Justo',
  'Buenos Aires',
  'AR',
  null,
  'https://jaquelinehilados.mitiendanube.com/',
  '-34.6781419',
  '-58.5588332',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-tristan-suarez-ezeiza-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Belgrano 54',
  'Tristán Suárez, Ezeiza',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.891375',
  '-58.567026',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-hurlingham-villa-tesei-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Sigmund Freud 3081',
  'Hurlingham, Villa Tesei',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.614015',
  '-58.633952',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-florencio-varela-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Monteagudo 3049, local 3',
  'Florencio Varela',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.806912',
  '-58.274605',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-san-martin-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Jose Hernandez 2949, Villa Ballester',
  'San Martín',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.548184',
  '-58.560802',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-chacabuco-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Almirante Brown 151',
  'Chacabuco',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.6436782',
  '-60.4741024',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-pablo-podesta-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Presidente Perón 9125',
  'Pablo Podestá',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.574131',
  '-58.610925',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-salto-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Dardo La Falce 25',
  'Salto',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.297',
  '-60.2418',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-berazategui-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Calle 53 3062',
  'Berazategui',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.808045',
  '-58.1864704',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-general-pacheco-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Hipólito Irigoyen',
  'General Pacheco',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.460329',
  '-58.633965',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-castelar-sur-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'William Morris 3673',
  'Castelar Sur',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.683762',
  '-58.659927',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-el-palomar-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Misiones 6564',
  'El Palomar',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.605405',
  '-58.594826',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-san-miguel-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Leandro N. Alem 1558',
  'San Miguel',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.543798',
  '-58.713061',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-olavarria-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Maipú 3146',
  'Olavarría',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-36.886764',
  '-60.3251916',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-ramos-mejia-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Av. San Martín 2017',
  'Ramos Mejía',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.659318',
  '-58.544769',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-pilar-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Hipólito Yrigoyen 457',
  'Pilar',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.457983',
  '-58.911157',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-san-martin-buenos-aires-2',
  'distributor',
  null,
  null,
  null,
  'Tucumán 2137',
  'San Martín',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.577336',
  '-58.539838',
  'approved',
  null,
  now()
),
(
  'Merceria Victoria',
  'merceria-victoria-quilmes-buenos-aires',
  'distributor',
  null,
  'https://www.merceriavictoria.com/',
  '541132160967',
  'Av. 12 de Octubre 1393',
  'Quilmes',
  'Buenos Aires',
  'AR',
  null,
  'https://www.merceriavictoria.com/',
  '-34.733621',
  '-58.272406',
  'approved',
  null,
  now()
),
(
  'Merceria Victoria',
  'merceria-victoria-quilmes-buenos-aires-2',
  'distributor',
  null,
  'https://www.merceriavictoria.com/',
  '541132160967',
  'Av. Rep. De Francia 2376',
  'Quilmes',
  'Buenos Aires',
  'AR',
  null,
  'https://www.merceriavictoria.com/',
  '-34.764538',
  '-58.264174',
  'approved',
  null,
  now()
),
(
  'Botón Once',
  'boton-once-caba-buenos-aires',
  'wholesaler',
  null,
  'https://www.botononce.com.ar/',
  '5491164708294',
  'Lavalle 2664',
  'CABA',
  'Buenos Aires',
  'AR',
  null,
  'https://www.botononce.com.ar/',
  '-34.603432',
  '-58.404602',
  'approved',
  null,
  now()
),
(
  'Merceril',
  'merceril-caba-buenos-aires',
  'wholesaler',
  null,
  'https://merceril.com.ar/',
  '5491128930968',
  'Paso 467',
  'CABA',
  'Buenos Aires',
  'AR',
  null,
  'https://merceril.com.ar/',
  '-34.603748',
  '-58.403359',
  'approved',
  null,
  now()
),
(
  'Casa Jorge',
  'casa-jorge-caba-buenos-aires',
  'wholesaler',
  null,
  'https://www.tiendacasajorge.com.ar/',
  '5491120401176',
  'Larrea 374',
  'CABA',
  'Buenos Aires',
  'AR',
  null,
  'https://www.tiendacasajorge.com.ar/',
  '-34.60529',
  '-58.402186',
  'approved',
  null,
  now()
),
(
  'Merceria Mayorista',
  'merceria-mayorista-olivos-buenos-aires',
  'wholesaler',
  null,
  null,
  null,
  'Luis Monteverde 4155',
  'Olivos',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.499841',
  '-58.498528',
  'approved',
  null,
  now()
),
(
  'Todo Vale',
  'todo-vale-alejandro-korn-buenos-aires',
  'distributor',
  null,
  null,
  '542224449254',
  'Av. Presidente Perón 5067',
  'Alejandro Korn',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.9840914',
  '-58.3751783',
  'approved',
  null,
  now()
),
(
  'Mas Lanas',
  'mas-lanas-lomas-de-zamora-buenos-aires',
  'wholesaler',
  null,
  null,
  null,
  'Gorriti 136',
  'Lomas de Zamora',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.7622037',
  '-58.3989596',
  'approved',
  null,
  now()
),
(
  'Mas Lanas',
  'mas-lanas-adrogue-buenos-aires',
  'wholesaler',
  null,
  null,
  null,
  'Mitre 1048',
  'Adrogué',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.7981427',
  '-58.3925534',
  'approved',
  null,
  now()
),
(
  'El Botón de Oro',
  'el-boton-de-oro-lanus-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Av. 9 de Julio 1326',
  'Lanús',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.7093471',
  '-58.3880652',
  'approved',
  null,
  now()
),
(
  'La Esquina de Olga Nube',
  'la-esquina-de-olga-nube-escobar-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Av. Eugenia T. de Cruz 998',
  'Escobar',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.350052',
  '-58.7974511',
  'approved',
  null,
  now()
),
(
  'Sewing World',
  'sewing-world-moreno-buenos-aires',
  'wholesaler',
  null,
  'https://sewingworld.com.ar/',
  '5491127370184',
  'Av. Bartolomé Mitre 3233',
  'Moreno',
  'Buenos Aires',
  'AR',
  null,
  'https://sewingworld.com.ar/',
  '-34.6473085',
  '-58.7956838',
  'approved',
  null,
  now()
),
(
  'Quiero Tejer',
  'quiero-tejer-moron-buenos-aires',
  'wholesaler',
  null,
  'https://www.quierotejer.com.ar/',
  '5491151541539',
  'Gral. Machado 878',
  'Morón',
  'Buenos Aires',
  'AR',
  null,
  'https://www.quierotejer.com.ar/',
  '-34.6465074',
  '-58.6206572',
  'approved',
  null,
  now()
),
(
  'Luis Lan Mercería',
  'luis-lan-merceria-moron-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Almte. Brown 646',
  'Morón',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.6506745',
  '-58.6179066',
  'approved',
  null,
  now()
),
(
  'Lolo Botón',
  'lolo-boton-ramos-mejia-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Av. San Martín 60',
  'Ramos Mejía',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.6423646',
  '-58.563129',
  'approved',
  null,
  now()
),
(
  'Adrine Mercería',
  'adrine-merceria-tres-de-febrero-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Av. La Plata 3621, Santos Lugares',
  'Tres de Febrero',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.6003014',
  '-58.5443674',
  'approved',
  null,
  now()
),
(
  'Ulylan',
  'ulylan-resistencia-chaco',
  'distributor',
  null,
  null,
  '5493624023112',
  'Julio A. Roca 372',
  'Resistencia',
  'Chaco',
  'AR',
  null,
  null,
  '-27.4489618',
  '-58.9905977',
  'approved',
  null,
  now()
),
(
  'Alvi Lanas',
  'alvi-lanas-resistencia-chaco',
  'distributor',
  null,
  null,
  '543624595237',
  'H. Irigoyen 295',
  'Resistencia',
  'Chaco',
  'AR',
  null,
  null,
  '-27.4524059',
  '-58.9830422',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-esquel-chubut',
  'distributor',
  null,
  null,
  null,
  'Sarmiento 567',
  'Esquel',
  'Chubut',
  'AR',
  null,
  null,
  '-42.9136411',
  '-71.3189353',
  'approved',
  null,
  now()
),
(
  'Como Ovillo al Dedo',
  'como-ovillo-al-dedo-corrientes-corrientes',
  'distributor',
  null,
  'https://comoovilloaldedo.com/',
  '543795574779',
  'Córdoba 951',
  'Corrientes',
  'Corrientes',
  'AR',
  null,
  'https://comoovilloaldedo.com/',
  '-27.468393',
  '-58.8343937',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-cordoba-capital-cordoba',
  'distributor',
  null,
  null,
  null,
  'Peatonal 25 de Mayo 225',
  'Córdoba Capital',
  'Córdoba',
  'AR',
  null,
  null,
  '-31.4155012',
  '-64.180413',
  'approved',
  null,
  now()
),
(
  'Mercecor Mayorista',
  'mercecor-mayorista-cordoba-capital-cordoba',
  'distributor',
  null,
  'https://mercecor.com.ar/',
  '543512275601',
  'Corrientes 226',
  'Córdoba Capital',
  'Córdoba',
  'AR',
  null,
  'https://mercecor.com.ar/',
  '-31.4203502',
  '-64.1824685',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-colon-entre-rios',
  'distributor',
  null,
  null,
  null,
  'Dr. Miguel Esteva Berga 73',
  'Colón',
  'Entre Ríos',
  'AR',
  null,
  null,
  '-32.222284',
  '-58.13825',
  'approved',
  null,
  now()
),
(
  'Sewing World',
  'sewing-world-mendoza-capital-mendoza',
  'distributor',
  null,
  'https://sewingworld.com.ar/',
  '542614254428',
  'Lavalle 72',
  'Mendoza Capital',
  'Mendoza',
  'AR',
  null,
  'https://sewingworld.com.ar/',
  '-32.8884507',
  '-68.8375663',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-obera-misiones',
  'distributor',
  null,
  null,
  null,
  'Tinogasta 949',
  'Oberá',
  'Misiones',
  'AR',
  null,
  null,
  '-27.4865616',
  '-55.1086079',
  'approved',
  null,
  now()
),
(
  'Mia Hilados Neuquén',
  'mia-hilados-neuquen-neuquen-capital-neuquen',
  'wholesaler',
  null,
  null,
  '542995502008',
  'Lainez 173',
  'Neuquén Capital',
  'Neuquén',
  'AR',
  null,
  null,
  '-38.9567344',
  '-68.0664705',
  'approved',
  null,
  now()
),
(
  'Tualana',
  'tualana-neuquen-capital-neuquen',
  'wholesaler',
  null,
  null,
  '5492236871679',
  'Alcorta 135',
  'Neuquén Capital',
  'Neuquén',
  'AR',
  null,
  null,
  '-38.9581015',
  '-68.061287',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-el-bolson-rio-negro',
  'distributor',
  null,
  null,
  null,
  'San Martín 2231',
  'El Bolsón',
  'Río Negro',
  'AR',
  null,
  null,
  '-41.9697544',
  '-71.5359471',
  'approved',
  null,
  now()
),
(
  'Merceria Variedades',
  'merceria-variedades-general-roca-rio-negro',
  'distributor',
  null,
  null,
  '542984414218',
  'Tucumán 1180',
  'General Roca',
  'Río Negro',
  'AR',
  null,
  null,
  '-39.027842',
  '-67.5810466',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-villa-regina-rio-negro',
  'distributor',
  null,
  null,
  null,
  'Av. Mitre 897',
  'Villa Regina',
  'Río Negro',
  'AR',
  null,
  null,
  '-39.10524927',
  '-67.08870461',
  'approved',
  null,
  now()
),
(
  'Mercería San Martín',
  'merceria-san-martin-salta-capital-salta',
  'distributor',
  null,
  null,
  null,
  'Av. San Martín 554',
  'Salta Capital',
  'Salta',
  'AR',
  null,
  null,
  '-24.7935946',
  '-65.4107041',
  'approved',
  null,
  now()
),
(
  'Punto y Puntada',
  'punto-y-puntada-san-juan-capital-san-juan',
  'distributor',
  null,
  null,
  '542644229822',
  'Tucumán Sur 22',
  'San Juan Capital',
  'San Juan',
  'AR',
  null,
  null,
  '-31.536342',
  '-68.525184',
  'approved',
  null,
  now()
),
(
  'Punto y Puntada',
  'punto-y-puntada-san-juan-capital-san-juan-2',
  'distributor',
  null,
  null,
  '542644229822',
  'Laprida 242 Este',
  'San Juan Capital',
  'San Juan',
  'AR',
  null,
  null,
  '-31.535213',
  '-68.522851',
  'approved',
  null,
  now()
),
(
  'Punto y Puntada',
  'punto-y-puntada-rivadavia-san-juan',
  'distributor',
  null,
  null,
  '542644229822',
  'Av. José Ignacio de la Roza Oeste 806',
  'Rivadavia',
  'San Juan',
  'AR',
  null,
  null,
  '-31.537158',
  '-68.541427',
  'approved',
  null,
  now()
),
(
  'Punto y Puntada',
  'punto-y-puntada-san-juan-capital-san-juan-3',
  'distributor',
  null,
  null,
  '542644229822',
  'Laprida 238 Este',
  'San Juan Capital',
  'San Juan',
  'AR',
  null,
  null,
  '-31.53521',
  '-68.5229',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-chimbas-san-juan',
  'distributor',
  null,
  null,
  null,
  'Oro 1575 Este, Barrio CGT',
  'Chimbas',
  'San Juan',
  'AR',
  null,
  null,
  '-31.49794757',
  '-68.51150799',
  'approved',
  null,
  now()
),
(
  'Roma Lanas',
  'roma-lanas-san-juan-capital-san-juan',
  'distributor',
  null,
  null,
  null,
  'Av. Ignacio de la Roza 244 Este, Galería Epicentro local 1',
  'San Juan Capital',
  'San Juan',
  'AR',
  null,
  null,
  '-31.536481',
  '-68.527315',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-caleta-olivia-santa-cruz',
  'distributor',
  null,
  null,
  null,
  'B. Mirador Brasil 250',
  'Caleta Olivia',
  'Santa Cruz',
  'AR',
  null,
  null,
  '-46.43632785',
  '-67.52910844',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-el-calafate-santa-cruz',
  'distributor',
  null,
  null,
  null,
  'Comandante Espora 65',
  'El Calafate',
  'Santa Cruz',
  'AR',
  null,
  null,
  '-50.334112',
  '-72.265241',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-juan-bernabe-molina-santa-fe',
  'distributor',
  null,
  null,
  null,
  'Moreno 470',
  'Juan Bernabé Molina',
  'Santa Fé',
  'AR',
  null,
  null,
  '-33.49228625',
  '-60.51124203',
  'approved',
  null,
  now()
),
(
  'Lanas Latorre',
  'lanas-latorre-rosario-santa-fe',
  'wholesaler',
  null,
  'https://lanaslatorre.com/',
  '543413691319',
  'Rioja 1319',
  'Rosario',
  'Santa Fé',
  'AR',
  null,
  'https://lanaslatorre.com/',
  '-32.945238',
  '-60.640102',
  'approved',
  null,
  now()
),
(
  'Distribuidor Mía',
  'distribuidor-mia-santiago-del-estero-capital-santiago-del-estero',
  'distributor',
  null,
  null,
  null,
  'Pellegrini 107',
  'Santiago del Estero Capital',
  'Santiago del Estero',
  'AR',
  null,
  null,
  '-27.785311',
  '-64.262194',
  'approved',
  null,
  now()
),
(
  'Araceli Mercería',
  'araceli-merceria-tafi-viejo-tucuman',
  'distributor',
  null,
  'https://aracelimarket.mitiendanube.com/',
  '5493815642024',
  'Uttinger 110',
  'Tafí Viejo',
  'Tucumán',
  'AR',
  null,
  'https://aracelimarket.mitiendanube.com/',
  '-26.732158',
  '-65.259421',
  'approved',
  null,
  now()
),
(
  'Makor S.A.',
  'makor-s-a-alvear-santa-fe',
  'wholesaler',
  null,
  'https://www.makorsa.com.ar/',
  '5493415045131',
  'Parque Industrial Avant Alvear AO12, Km 5, S2130 Alvear, Santa Fe',
  'Alvear',
  'Santa Fé',
  'AR',
  null,
  'https://www.makorsa.com.ar/',
  '-33.0890767',
  '-60.6814957',
  'approved',
  null,
  now()
),
(
  'La casa de las lanas',
  'la-casa-de-las-lanas-puerto-madryn-chubut',
  'distributor',
  null,
  null,
  null,
  'Belgrano 126',
  'Puerto Madryn',
  'Chubut',
  'AR',
  null,
  null,
  '-42.7673178',
  '-65.034674',
  'approved',
  null,
  now()
),
(
  'La casa de las lanas',
  'la-casa-de-las-lanas-trelew-chubut',
  'wholesaler',
  null,
  null,
  null,
  'San Martin 160',
  'Trelew',
  'Chubut',
  'AR',
  null,
  null,
  '-43.2532857',
  '-65.307816',
  'approved',
  null,
  now()
),
(
  'La casa de las lanas',
  'la-casa-de-las-lanas-rawson-chubut',
  'distributor',
  null,
  null,
  null,
  'Lewis jhones 316',
  'Rawson',
  'Chubut',
  'AR',
  null,
  null,
  '-43.2995252',
  '-65.1055636',
  'approved',
  null,
  now()
),
(
  'Otoño Lanas',
  'otono-lanas-comodoro-rivadavia-chubut',
  'distributor',
  null,
  null,
  null,
  'San Lorenzo 1521',
  'Comodoro Rivadavia',
  'Chubut',
  'AR',
  null,
  null,
  '-45.7965245',
  '-67.472909',
  'approved',
  null,
  now()
),
(
  'Polirrubro "el colo"',
  'polirrubro-el-colo-lamarque-rio-negro',
  'distributor',
  null,
  null,
  null,
  'Islas Malvinas 366',
  'Lamarque',
  'Río Negro',
  'AR',
  null,
  null,
  '-39.4162192',
  '-65.698254',
  'approved',
  null,
  now()
),
(
  'Mercería Entre Hilos',
  'merceria-entre-hilos-las-grutas-rio-negro',
  'distributor',
  null,
  null,
  null,
  'Río negro 870',
  'Las Grutas',
  'Río Negro',
  'AR',
  null,
  null,
  '-40.8097748',
  '-65.0913257',
  'approved',
  null,
  now()
),
(
  'La casa de las lanas',
  'la-casa-de-las-lanas-tres-lomas-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'Antártida Argentina 684',
  'Tres Lomas',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-36.4536745',
  '-62.8533381',
  'approved',
  null,
  now()
),
(
  'Trilanas',
  'trilanas-viedma-rio-negro',
  'distributor',
  null,
  null,
  '542920629386',
  'Alvear 1183',
  'Viedma',
  'Río Negro',
  'AR',
  null,
  null,
  '-40.8083811',
  '-63.0050771',
  'approved',
  null,
  now()
),
(
  'Entretejiendo',
  'entretejiendo-carhue-buenos-aires',
  'distributor',
  null,
  null,
  null,
  'San Martín 926',
  'Carhué',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-37.1796063',
  '-62.758218',
  'approved',
  null,
  now()
),
(
  'La Casita Azul',
  'la-casita-azul-trevelin-chubut',
  'distributor',
  null,
  null,
  '542945533242',
  'San Martin 1400',
  'Trevelin',
  'Chubut',
  'AR',
  null,
  null,
  '-43.0957054',
  '-71.4638899',
  'approved',
  null,
  now()
),
(
  'Tienda Luno',
  'tienda-luno-caba-buenos-aires',
  'distributor',
  null,
  null,
  '541139423630',
  'Av. Nazca 1092',
  'CABA',
  'Buenos Aires',
  'AR',
  null,
  null,
  '-34.6208048',
  '-58.4742252',
  'approved',
  null,
  now()
),
(
  'Merceria telas y lanas "Carovane"',
  'merceria-telas-y-lanas-carovane-las-heras-santa-cruz',
  'distributor',
  null,
  null,
  null,
  'Calafate 324',
  'Las Heras',
  'Santa Cruz',
  'AR',
  null,
  null,
  '-46.5500526',
  '-68.9228482',
  'approved',
  null,
  now()
),
(
  'Juliette Mercería',
  'juliette-merceria-villa-regina-rio-negro',
  'distributor',
  null,
  null,
  '542966477190',
  'JOSE INGENIEROS, ESQ Alejandro Adrian Bonani',
  'Villa Regina',
  'Río Negro',
  'AR',
  null,
  null,
  '-39.0987',
  '-67.0852',
  'approved',
  null,
  now()
),
(
  'JB Distribuidora',
  'jb-distribuidora-santa-rosa-la-pampa',
  'distributor',
  null,
  null,
  null,
  'Av. Luro 1669',
  'Santa Rosa',
  'La Pampa',
  'AR',
  null,
  null,
  '-36.6335386',
  '-64.2819769',
  'approved',
  null,
  now()
),
(
  'Faisaflor Lanas',
  'faisaflor-lanas-buenos-aires-buenos-aires',
  'distributor',
  null,
  'https://www.faisaflor.com.ar/',
  '5491123022340',
  null,
  'Buenos Aires',
  'Buenos Aires',
  'AR',
  null,
  'https://www.faisaflor.com.ar/',
  '-34.6037',
  '-58.3816',
  'approved',
  null,
  now()
)
on conflict (slug) do update
set
  provider_type = excluded.provider_type,
  phone = excluded.phone,
  address = excluded.address,
  city = excluded.city,
  province = excluded.province,
  country = excluded.country,
  website = excluded.website,
  latitude = excluded.latitude,
  longitude = excluded.longitude,
  status = excluded.status,
  approved_at = excluded.approved_at;